const fs = require('fs');
const path = 'e:\\vivpr\\ai\\collect-list\\extension\\translations.js';

const I18N_DATA = {
    "en": {
        "app_title": "X PIDER-Local Business Data Crawler",
        "app_subtitle": "Collect Business Data from the Web",
        "tab_text": "Text Data",
        "tab_link": "Link/URL",
        "tab_search": "Search Engine",
        "tab_settings": "⚙️ Settings",
        "placeholder_text_input": "Paste text containing business names...",
        "placeholder_url_input": "http://www.yellopage.org/los-angeles-ca/plumber...",
        "placeholder_keyword_input": "Search keyword (e.g., Cafe in NY)",
        "label_depth": "Depth",
        "label_steps": "steps",
        "depth_info_1": "1-99 Levels: Continuous Scroll & Pagination",
        "engine_all": "🌐 All-in-One Search",
        "group_main_engines": "🔍 Search Engines",
        "engine_google": "🔵 Google",
        "engine_naver": "🟢 Naver (KR)",
        "engine_yahoo": "🟣 Yahoo",
        "engine_yahoojp": "🔴 Yahoo Japan",
        "group_business_social": "💼 Business & Social",
        "engine_yelp": "🔴 Yelp",
        "engine_linkedin": "🔵 LinkedIn",
        "engine_facebook": "🔵 Facebook",
        "engine_google_fb": "🔵 Facebook (No Login)",
        "engine_google_li": "🔵 LinkedIn (No Login)",
        "group_shopping_market": "🛒 Shopping & Market",
        "engine_amazon": "🟡 Amazon",
        "engine_etsy": "🟠 Etsy",
        "label_search_range": "Search Range",
        "label_pages": "pages",
        "search_info_max": "Max 99 pages (Auto Paging Support)",
        "label_system_lang": "🌐 System Language",
        "label_search_region": "📍 Target Region",
        "btn_save_settings": "💾 Save & Apply Settings",
        "btn_start": "Start Collection",
        "label_email_scan": "Deep scan for emails",
        "status_title": "Progress",
        "stats_prefix": "Found ",
        "stats_suffix": " valid items",
        "result_title": "Collection results so far",
        "btn_download": "Download CSV",
        "col_name": "Business Name",
        "col_address": "Address",
        "col_url": "Website",
        "col_sns": "Social Media",
        "col_email": "Email",
        "col_phone": "Phone",
        "msg_saved": "✅ Applied!",
        "alert_empty": "Please enter content.",
        "log_crawl_start": "🛳️ Crawling exploration started...",
        "log_crawl_searching": "🌐 Exploring: {url}",
        "log_crawl_finished": "🏁 Crawling finished. Parsing {count} targets.",
        "log_email_searching": "📧 [{index}/{total}] Searching email for '{name}'...",
        "log_search_searching": "🌐 [{index}/{total}] Searching for '{name}'...",
        "log_visit_email": "📧 Visiting site to collect emails...",
        "log_engine_start": "🚀 Collection started (Region: {region}, Lang: {lang})",
        "log_platform_searching": "🌐 [{engine}] Exploring platform...",
        "log_page_processing": "📄 [{engine}] Processing page {page}/{max}...",
        "log_engine_finished": "🏁 [{engine}] Collection finished. Moving next in 5s...",
        "log_complete": "All tasks completed.",
        "log_error": "Fatal Error: {msg}",
        "log_skip": "⚠️ Skipping access: {url}",
        "log_linkedin_warn": "⚠️ LinkedIn may require login.",
        "log_facebook_warn": "⚠️ Facebook requires login.",
        "log_bypass_active": "🛡️ Using Google site: search (Login Bypass Mode)",
        "label_select_all": "🌐 Select All Engines",
        "engine_selected": "{count} Engines Selected",
        "btn_cancel": "🛑 Stop Collection",
        "btn_download_csv": "📊 CSV",
        "btn_download_txt": "📄 TXT",
        "btn_download_gs": "📈 Sheets",
        "log_cancelled": "🛑 Collection stopped by user.",
        "label_deep_page": "Deep Search Depth",
        "deep_info_desc": "Sub-level exploration per item",
        "already_searching": "⚠️ Collection already in progress. Please wait.",
        "log_preparing": "🔄 Preparing for collection...",
        "log_waiting_engine": "⏳ {engine} waiting for results...",
        "log_skip_listing": "Search listing title excluded",
        "no_results": "No results found.",
        "no_valid_names": "🛑 No valid business names found.",
        "log_text_start_init": "📄 Received text for analysis ({count} chars). Processing...",
        "log_text_start": "📄 Starting collection ({count} valid names found)",
        "stage1Done": "Stage 1 done",
        "namesCollected": " names collected!",
        "stage2Start": "Stage 2 search starting...",
        "searching": "Searching...",
        "stage3DeepScan": "Homepage deep scan",
        "nonLocal": "Non-local excluded",
        "log_items_received": "{count} items received",
        "log_skip_serp": "  🚫 [{index}/{total}] \"{name}\" ➔ SERP noise excluded",
        "log_skip_filter": "  🚫 [{index}/{total}] \"{name}\" ➔ {reason}",
        "log_skip_filter_default": "Positive filter failed",
        "log_captcha_detected": "⚠️ CAPTCHA detected! Google has blocked automated collection. Please solve the CAPTCHA below; collection will resume automatically.",
        "log_captcha_solved": "✅ CAPTCHA solved. Continuing...",
        "log_taking_break": "☕ Taking a break to avoid blocks ({seconds}s)...",
        "captcha_popup_title": "⚠️ CAPTCHA Detected",
        "captcha_popup_msg": "Google has blocked automated collection. Please solve the CAPTCHA below; collection will resume automatically.",
        "target_extraction": "Target Extraction",
        "target_desc": "In-depth scraping focused on selected info",
        "target_all": "🌐 All Business Info",
        "target_name": "🏗️ business name",
        "target_webpage": "🌐 website (URL)",
        "target_address": "📍 address",
        "target_phone": "📞 phone",
        "target_email": "📧 email",
        "target_sns": "💬 sns",
        "stats_target_prefix": "Found ",
        "log_level_processing": "[Level {level}/{total}] Processing: {url}",
        "log_level_found": "  🔍 Level {level}: Found {count} items (New: {newCount})",
        "log_level_finished": "  🏁 Continuous discovery finished (End of list).",
        "log_level_navigating": "  ➔ Navigating to Level {next} ({type})...",
        "log_unified_scan": "  🌐 [Unified Algorithm] Performing full text scan on Search Engine page ({lang})...",
        "log_unified_count": "  📊 Unified Algorithm: Added {count} extra candidates from SERP text.",
        "log_no_valid_after_filter": "  ⚠️ No valid business names found after noise filtering.",
        "log_received_clean": "  ✅ Received {count} clean results. Enriching...",
        "log_timeout_skip": "  ⚠️ [Timeout] {name} enrichment taking too long. Skipping to next item.",
        "log_page_timeout": "  ⚠️ [Page Timeout] Scanning took too long. Skipping this page/level.",
        "log_finished_overall": "Collection process completely finished.",
        "status_stopping": "🛑 Stopping... Please wait",
        "status_finished": "Collection Status: {count} extracted",
        "label_download_title": "DOWNLOAD"
    },
    "ko": {
        "app_title": "X PIDER-Local Business Data Crawler",
        "app_subtitle": "웹에서 비즈니스 데이터 수집",
        "tab_text": "텍스트 수집",
        "tab_link": "링크 수집",
        "tab_search": "검색엔진 수집",
        "tab_settings": "⚙️ 설정",
        "placeholder_text_input": "업체명이 포함된 텍스트를 붙여넣으세요...",
        "placeholder_url_input": "http://www.yellopage.org/los-angeles-ca/plumber...",
        "placeholder_keyword_input": "검색 키워드 입력 (예: 강남구 카페)",
        "label_depth": "탐색 깊이",
        "label_steps": "단계",
        "depth_info_1": "1~99단계: 연속 스크롤 및 자동 페이지 수집",
        "engine_all": "🌐 전체 플랫폼 검색 (All in One)",
        "group_main_engines": "🔍 주요 검색 엔진",
        "engine_google": "🔵 구글 코리아 (Google KR)",
        "engine_naver": "🟢 Naver (네이버)",
        "engine_yahoo": "🟣 Yahoo (야후)",
        "engine_yahoojp": "🔴 Yahoo 재팬",
        "engine_bing": "🔵 Bing (빙)",
        "group_map_engines": "📍 지역 기반 장소 서치 (강력 권장)",
        "engine_google_maps": "📍 구글 코리아 지도 (Google Maps KR)",
        "engine_naver_place": "📍 네이버 플레이스 (Naver Place)",
        "engine_yahoo_maps": "📍 야후 재팬 지도 (Yahoo Japan Maps)",
        "engine_bing_maps": "📍 빙 지도 (Bing Maps)",
        "group_business_social": "💼 비즈니스 & 소셜",
        "engine_yelp": "🔴 Yelp (옐프)",
        "engine_linkedin": "🔵 LinkedIn (링크드인)",
        "engine_facebook": "🔵 Facebook (페이스북)",
        "engine_google_fb": "🔵 Facebook (로그인 우회)",
        "engine_google_li": "🔵 LinkedIn (로그인 우회)",
        "group_shopping_market": "🛒 쇼핑 & 마켓",
        "engine_amazon": "🟡 Amazon (아마존)",
        "engine_etsy": "🟠 Etsy (엣시)",
        "label_search_range": "검색 범위",
        "label_pages": "페이지까지",
        "search_info_max": "최대 99페이지 (자동 페이지 스크롤 지원)",
        "label_system_lang": "🌐 시스템 언어 (Language)",
        "label_search_region": "📍 검색 대상 지역 (Region)",
        "btn_save_settings": "💾 설정 저장 및 적용",
        "btn_start": "데이터 수집 시작",
        "label_email_scan": "하위 페이지까지 딥스캔 이메일 수집",
        "status_title": "진행 상황",
        "stats_prefix": "유효 데이터",
        "stats_suffix": "개 발견됨",
        "result_title": "현재까지 수집결과",
        "btn_download": "CSV 다운로드",
        "col_name": "업체명",
        "col_address": "주소",
        "col_url": "홈페이지",
        "col_sns": "소셜미디어",
        "col_email": "이메일",
        "col_phone": "전화번호",
        "msg_saved": "✅ 저장 완료!",
        "alert_empty": "내용을 입력해주세요.",
        "log_crawl_start": "🛳️ 크롤링 탐색을 시작합니다...",
        "log_crawl_searching": "🌐 탐색 중: {url}",
        "log_crawl_finished": "🏁 크롤링 완료. {count}개의 분석 대상을 파싱합니다.",
        "log_email_searching": "📧 [{index}/{total}] '{name}' 이메일 탐색...",
        "log_search_searching": "🌐 [{index}/{total}] '{name}' 검색 중..",
        "log_visit_email": "📧 사이트 방문하여 이메일 수집 중..",
        "log_engine_start": "🚀 수집 시작 (지역: {region}, 언어: {lang})",
        "log_platform_searching": "🌐 [{engine}] 플랫폼 탐색 중..",
        "log_page_processing": "📄 [{engine}] {page}/{max} 페이지 처리 중..",
        "log_engine_finished": "🏁 [{engine}] 수집 완료. 5초 후 다음 이동...",
        "log_complete": "모든 작업이 완료되었습니다.",
        "log_error": "치명적 오류: {msg}",
        "log_skip": "⚠️ 접속 건너뜀: {url}",
        "log_linkedin_warn": "⚠️ LinkedIn은 로그인이 필요할 수 있습니다.",
        "log_facebook_warn": "⚠️ Facebook은 로그인이 필요합니다.",
        "log_bypass_active": "🛡️ 구글 site: 검색 연산자를 이용한 모드로 전환합니다 (로그인 우회).",
        "btn_cancel": "수집 중단",
        "status_stopping": "🛑 중단 중.. 잠시만 기다려주세요",
        "status_finished": "수집 상황: {count}개 추출",
        "label_download_title": "다운로드"
    }
};

const filePrefix = "var I18N_DATA = ";
const fileSuffix = ";";

fs.writeFileSync(path, filePrefix + JSON.stringify(I18N_DATA, null, 4) + fileSuffix, 'utf8');
console.log('File fully reconstructed with clean data.');
