const fs = require('fs');
let html = fs.readFileSync('E:/vivpr/ai/full-xpider-full/landing/index.html', 'utf8');
const dictionary = [
  ['XPIDER Browser | 마케팅 자동화의 혁신적 진화', 'XPIDER Browser | Innovative Evolution of Marketing Automation'],
  ['작업은 단순하게, 결과는 극대화로. 구글맵 수집, 자동 폼 발송, 대량 메일러, 로컬 릴레이 VPN까지 올인원 마케팅 브라우저 XPIDER를 만나보세요.', 'Simplify tasks, maximize results. Meet XPIDER, the all-in-one marketing browser featuring Google Maps scraper, auto form sender, mass mailer, and local relay VPN.'],
  ['XPIDER, 마케팅 자동화, 구글맵 수집기, 자동 폼 발송기, 대량 메일 발송, 마케팅 브라우저, Extensions, VPN', 'XPIDER, Marketing Automation, Google Maps Scraper, Auto Form Sender, Mass Mailer, Marketing Browser, Extensions, VPN'],
  ['비즈니스 데이터 수집부터 폼 발송, 자동 Email 캠페인까지. 마케터들의 작업을 단순화하는 프리미엄 올인원 브라우저.', 'From business data collection to form sending and automated email campaigns. A premium all-in-one browser that simplifies marketers tasks.'],
  ['정식 버전', 'Official Version'],
  ['정식 릴리즈 완료', 'Official Release Complete'],
  ['Extensions 살펴보기', 'Explore Extensions'],
  ['자세히 보기 →', 'Learn More →'],
  ['핵심 기능', 'Core Features'],
  ['6대 Extensions', 'Top 6 Extensions'],
  ['무료 다운로드', 'Free Download'],
  ['다운로드', 'Download'],
  ['실시간 693+ 무작위 증가 및 무한 스크롤 피드 동기화 스크립트', 'Real-time 693+ random increment and infinite scroll feed sync script'],
  ['고품질 무한 가상 기업 데이터 풀', 'High-quality infinite virtual enterprise data pool'],
  ['헤라 뷰티 클리닉 - 미용/에스테틱', 'Hera Beauty Clinic - Beauty/Aesthetics'],
  ['미래 부동산 컨설팅 - 공인중개', 'Mirae Real Estate Consulting - Realtors'],
  ['한샘 푸드 시스템 - 식자재/유통', 'Hanssem Food System - Food/Distribution'],
  ['더 파크 펜션 - 관광/숙박', 'The Park Pension - Tourism/Accommodation'],
  ['에이펙스 마케팅 - 광고 대행', 'Apex Marketing - Advertising Agency'],
  ['오션 드라이브 - 렌터카/운송', 'Ocean Drive - Rent-a-car/Transport'],
  ['바른 덴탈 클리닉 - 병의원', 'Barun Dental Clinic - Clinic'],
  ['빛나는 영어 학원 - 초중고 교육', 'Shining English Academy - Education'],
  ['제이앤씨 디자인 - 인테리어/건축', 'J&C Design - Interior/Architecture'],
  ['유니온 법률사무소 - 전문서비스', 'Union Law Firm - Professional Services'],
  ['스마트 피트니스 - 헬스/PT', 'Smart Fitness - Health/PT'],
  ['그린 에코 하우스 - 친환경 자재', 'Green Eco House - Eco-friendly Materials'],
  ['문의 제안 폼', 'Contact Suggestion Form'],
  ['비즈니스 웹사이트 추출 완료', 'Business Website Extraction Complete'],
  ['콘택트 Message 폼 발견', 'Contact Message Form Discovered'],
  ['캡차 시큐리티(CAPTCHA) 발견', 'CAPTCHA Security Discovered'],
  ['캡차 자동 우회 완료', 'CAPTCHA Auto-Bypass Complete'],
  ['폼 자동 입력 시작...', 'Starting Auto Form Input...'],
  ['XPIDER를 통한 자동 제안 Message입니다.', 'This is an automated proposal message sent via XPIDER.'],
  ['구글맵 기반 초고속 가망고객 정보 전수 추출기', 'Google Maps-based Ultra-fast Prospect Information Extractor'],
  ['GMaps Finder는 전 세계 구글맵(Google Maps) 및 포털 플랫폼에 등록된 비즈니스 정보를 단 몇 초 만에 전수 추출하는 혁신적인 자동 스크래핑 Extensions입니다. 타겟 업종과 검색 영역(마일 단위 정밀 설정)을 입력하는 즉시, 사업체의 실시간 전화번호, 정확한 비즈니스 소유주 정보, 홈페이지 링크, 활성화된 Email 주소까지 누수 없이 수집하여 고품질 마케팅 DB를 즉각 구축합니다.', 'GMaps Finder is an innovative auto-scraping extension that fully extracts business information registered on Google Maps and portal platforms worldwide in just a few seconds. Immediately after entering target industries and search areas, it accurately collects business phone numbers, owner info, website links, and active email addresses to build a high-quality marketing DB.'],
  ['초고속 병렬 추출 기술', 'Ultra-fast Parallel Extraction Technology'],
  ['여러 탭을 동시에 다중 스캔하여 몇 분 만에 수천 개의 고가치 리드를 수집합니다.', 'Scans multiple tabs simultaneously to collect thousands of high-value leads in minutes.'],
  ['숨겨진 홈페이지 정보 발굴', 'Discover Hidden Website Information'],
  ['사이트 도메인 내부를 실시간으로 탐색해 SNS 프로필 및 유효 메일 주소를 가로챕니다.', 'Explores site domains in real-time to intercept SNS profiles and valid email addresses.'],
  ['스마트 우회 & CAPTCHA 대응', 'Smart Bypass & CAPTCHA Handling'],
  ['차단 감지 시 즉각 스캔을 임시 중단하고 유저의 검증 처리가 끝나면 일제히 동시 재개합니다.', 'Temporarily suspends scanning upon block detection and resumes simultaneously after user verification.'],
  ['원클릭 정제 및 엑셀 다운로드', 'One-click Refinement and Excel Download'],
  ['중복된 연락처나 무효 도메인을 필터링하여 완벽한 CSV/Excel 파일로 내보냅니다.', 'Filters duplicate contacts and invalid domains to export a perfect CSV/Excel file.'],
  ['최신 프레임워크 인간형 문의폼 우회 발송기', 'Latest Framework Humanoid Contact Form Bypass Sender'],
  ['인간형 타이핑 및 마우스 시뮬레이션', 'Humanoid Typing and Mouse Simulation'],
  ['기계적인 입력을 배제하고 자연스러운 타이핑 속도 및 마우스 궤적을 완벽 모사합니다.', 'Excludes mechanical inputs and perfectly simulates natural typing speed and mouse trajectories.'],
  ['스마트 동적 iframe 폼 필드 감지', 'Smart Dynamic iframe Form Field Detection'],
  ['숨겨진 dynamic iframe 및 중첩된 TPA 폼 필드까지 지능적으로 자동 감지합니다.', 'Intelligently auto-detects hidden dynamic iframes and nested TPA form fields.'],
  ['스마트 CAPTCHA 우회 프로세스', 'Smart CAPTCHA Bypass Process'],
  ['구글 리캡차(CAPTCHA) 등 각종 방어막을 자동 감지하고 유저 검증 시 실시간으로 대응합니다.', 'Auto-detects Google reCAPTCHA and other defenses, responding in real-time upon user verification.'],
  ['추출된 잠재 고객을 위한 고밀도 맞춤형 Email 자동 발송기', 'High-density Customized Email Auto Sender for Extracted Prospects'],
  ['SendForce Mailer는 추출된 대규모 잠재 고객 Email 리스트를 향해 고밀도 맞춤형(Personalized) 자동화 메일을 즉각적으로 대량 발송합니다. 강력한 SMTP 로테이션 시스템을 적용해 스팸 필터링을 최소화하고, 수신율과 오픈율을 극대화하여 마케팅 ROI의 비약적 향상을 보장합니다.', 'SendForce Mailer instantly sends high-density customized automated emails to large-scale extracted prospect email lists. By applying a powerful SMTP rotation system, it minimizes spam filtering and maximizes delivery and open rates to ensure a leap in marketing ROI.'],
  ['초고속 대량 메일 발송', 'Ultra-fast Mass Mail Sending'],
  ['클라우드 기반 병렬 스레드를 통해 수만 건의 Email을 지연 없이 즉각적으로 전송합니다.', 'Instantly sends tens of thousands of emails without delay via cloud-based parallel threads.'],
  ['개인화 매개변수 적용', 'Apply Personalization Parameters'],
  ['수신자의 이름, 상호명 등 커스텀 변수를 자동으로 삽입하여 1:1 맞춤 메일인 것처럼 구성합니다.', 'Automatically inserts custom variables like recipient name and business name to compose 1:1 personalized emails.'],
  ['지능형 SMTP 로테이션', 'Intelligent SMTP Rotation'],
  ['여러 SMTP 서버를 동적으로 교체하며 발송하여 서버의 스팸 패널티를 사전에 회피합니다.', 'Dynamically alternates multiple SMTP servers to proactively avoid server spam penalties.'],
  ['실시간 성과 트래킹', 'Real-time Performance Tracking'],
  ['Email 오픈율, 클릭률, 반송률 등 캠페인의 성과 지표를 실시간 대시보드로 제공합니다.', 'Provides campaign performance metrics like email open rate, click rate, and bounce rate via real-time dashboard.'],
  ['ERR_TUNNEL 문제를 완벽 우회하는 안전 프록시 통신', 'Secure Proxy Communication that Perfectly Bypasses ERR_TUNNEL Issues'],
  ['XPIDER Secure VPN은 기존 크로미움 브라우저에서 빈번하게 발생하는 프록시 인증 충돌(ERR_TUNNEL_CONNECTION_FAILED) 문제를 근본적으로 해결하기 위해 개발된 127.0.0.1 로컬 릴레이 가상 터널 방식의 차세대 VPN Extensions입니다.', 'XPIDER Secure VPN is a next-generation VPN extension using a 127.0.0.1 local relay virtual tunnel, developed to fundamentally resolve the proxy authentication conflict (ERR_TUNNEL_CONNECTION_FAILED) that frequently occurs in Chromium browsers.'],
  ['로컬 릴레이 통신 기술', 'Local Relay Communication Technology'],
  ['외부 프록시로 직접 연결하지 않고 로컬호스트(127.0.0.1)를 경유하여 브라우저 엔진의 인증 충돌을 방지합니다.', 'Prevents browser engine authentication conflicts by routing through localhost (127.0.0.1) instead of connecting directly to an external proxy.'],
  ['글로벌 다국적 서버 지원', 'Global Multi-national Server Support'],
  ['12개국 이상의 초고속 글로벌 프록시 서버망을 지원하여 타겟 국가의 로컬 비즈니스 정보를 안전하게 수집할 수 있습니다.', 'Supports an ultra-fast global proxy server network across 12+ countries to securely collect local business info in target countries.'],
  ['초저지연 데이터 터널링', 'Ultra-low Latency Data Tunneling'],
  ['마케팅 데이터 수집과 폼 발송에 최적화된 저지연 통신망을 제공하여 추출 속도 저하를 막습니다.', 'Provides low-latency communication optimized for marketing data collection and form sending to prevent extraction slowdowns.'],
  ['IP 핑거프린트 추적 방어', 'IP Fingerprint Tracking Defense'],
  ['발송자의 실제 IP와 식별값을 완벽하게 마스킹하여 보안 시스템의 계정 차단을 회피합니다.', 'Perfectly masks the sender actual IP and identifiers to bypass security system account blocks.'],
  ['실시간 Email 하베스팅 및 유실 없는 고객 리스트 추출기', 'Real-time Email Harvesting and Lossless Customer List Extractor'],
  ['Email Extractor는 브라우저 내에 활성화된 모든 탭의 DOM과 네트워크 통신을 실시간으로 감시하여, 화면에 노출되거나 소스 코드 내에 은닉된 Email 주소를 1초 만에 가로채는 지능형 리드 수집 솔루션입니다.', 'Email Extractor is an intelligent lead collection solution that monitors the DOM and network communication of all active tabs in real-time, intercepting email addresses exposed on screen or hidden in source code within seconds.'],
  ['실시간 라이브 추출', 'Real-time Live Extraction'],
  ['웹 페이지를 탐색하는 즉시, 렌더링된 화면과 소스 코드에서 Email 패턴을 감지하여 실시간으로 수집합니다.', 'As soon as a webpage is browsed, it detects and collects email patterns from the rendered screen and source code in real-time.'],
  ['강력한 난독화 해제 기능', 'Powerful De-obfuscation Feature'],
  ['JS나 CSS로 교묘하게 숨겨진 Email 주소(난독화 처리)를 자체 엔진으로 해독하여 온전한 형태로 가로챕니다.', 'Decodes email addresses cleverly hidden via JS or CSS (obfuscation) using a proprietary engine to intercept them intact.'],
  ['수집된 방대한 Email 리스트에서 중복값을 자동으로 필터링하고 CSV/Excel 포맷으로 원클릭 내보내기를 지원합니다.', 'Automatically filters duplicates from the vast collected email list and supports one-click export to CSV/Excel format.'],
  ['추출 완료 즉시 Email 자동 발송기(SendForce)와 연동 가능한 고품질 스프레드시트 포맷으로 반환합니다.', 'Returns a high-quality spreadsheet format instantly compatible with the email auto sender (SendForce) upon extraction completion.'],
  ['XPIDER는 단순한 Extensions 모음이 아니라, 마케팅 특화 프로세스를 크로미움(Chromium) 엔진 자체에 통합한 전 세계 유일의 독립 브라우저 솔루션입니다. 특히 Wix나 React와 같은 신형 프레임워크 폼 전송 시, 기계가 아닌 실제 마우스 드래그와 인간형 키보드 타이핑 모션(insertText)을 완벽하게 동기화하기 때문에 사이트의 봇 탐지 솔루션에 걸리지 않는 압도적인 성공률을 보여줍니다.', 'XPIDER is not just a collection of extensions, but the world only independent browser solution that integrates marketing-specific processes directly into the Chromium engine. Especially when submitting forms on modern frameworks like Wix or React, it perfectly synchronizes actual mouse drags and humanoid keyboard typing motions (insertText) rather than mechanical inputs, resulting in an overwhelming success rate that evades site bot detection solutions.'],
  ['타사의 메일 자동화 플랫폼은 고정된 Email 서버를 사용하여 쉽게 스팸으로 분류되거나, 타겟 리스트를 수동으로 업로드해야 하는 번거로움이 있습니다. 반면 XPIDER의 SendForce Mailer는 <b>추출기(GMaps Finder, Email Extractor)와 직접 연동</b>되어 실시간으로 수집된 리스트에 즉각 발송을 시작합니다. 또한 <b>지능형 SMTP 로테이션 시스템</b>과 개인화 매개변수 삽입 기능을 통해 스팸 필터링을 극강으로 억제하며 오픈율을 극대화합니다.', 'Third-party mail automation platforms use fixed email servers, making them easily flagged as spam or requiring the hassle of manual target list uploads. In contrast, XPIDER SendForce Mailer <b>integrates directly with extractors (GMaps Finder, Email Extractor)</b> to instantly start sending to real-time collected lists. Furthermore, through an <b>intelligent SMTP rotation system</b> and personalized parameter insertion, it strictly suppresses spam filtering and maximizes open rates.'],
  ['추출된 잠재 고객 Email 리스트를 향해 고밀도 맞춤형 자동화 메일을 즉각 대량 발송합니다.', 'Instantly sends high-density customized automated emails to the extracted prospect email list.'],
  ['브라우저 내 활성화된 탭에서 Email 주소를 실시간으로 가로채어 유실 없는 고객 리스트를 추출합니다.', 'Intercepts email addresses in real-time from active tabs in the browser to extract a lossless customer list.']
];

dictionary.forEach(([ko, en]) => {
  html = html.split(ko).join(en);
});
fs.writeFileSync('E:/vivpr/ai/full-xpider-full/landing/index.html', html);
console.log('Translated main texts successfully.');
