const translations = {
    ko: {
        app_title: "XPIDER 브라우저",
        back: "뒤로",
        forward: "앞으로",
        reload: "새로고침",
        placeholder_url: "URL 입력 또는 검색...",
        themes: "테마",
        languages: "언어",
        update_available: "업데이트 가능...",
        restart: "재시작",
        add_page: "페이지 추가",
        hide_sidebar: "사이드바 숨기기",
        ob_welcome: "Welcome to XPIDER",
        ob_subline: "세계 최강의 비즈니스 데이터 수집 브라우저",
        ob_next: "다음",
        ob_close: "시작하기",
        ob_dont_show: "다시 보지 않기",
        check_update: "업데이트 확인",
        welcome_msg: "XPIDER 브라우저에 오신 것을 환영합니다",
        
        // Card 1: Local Business Crawler Pro
        ob_c1_title: "Local Business Crawler",
        ob_c1_ver: "Pro",
        ob_c1_sub: "검색엔진을 가로질러 — 업체명 하나가 완전한 리드로",
        ob_c1_desc: "구글·네이버·빙 등 10개 검색엔진에서 키워드 검색 후, 업체명·홈페이지·컨택 페이지를 자동 추적하여 이메일·전화·주소·SNS까지 한 번에 수집합니다.",
        ob_c1_t1: "🔍 4단계 딥스캔",
        ob_c1_t2: "📧 이메일 자동추출",
        ob_c1_t3: "🤖 캡차 자동우회",

        // Card 2: GMaps Business Finder
        ob_c2_title: "GMaps Business Finder",
        ob_c2_ver: "v1.1.0",
        ob_c2_sub: "지도 위 모든 업체를 — 고품질 리드 리스트로 변환",
        ob_c2_desc: "구글 맵에서 검색어로 주변 업체를 탐색하고, 업체명·별점·전화·홈페이지·이메일을 실시간으로 발굴합니다. CSV/JSON 즉시 내보내기 지원.",
        ob_c2_t1: "📍 위치기반 수집",
        ob_c2_t2: "⭐ 별점 필터",
        ob_c2_t3: "📊 CSV 내보내기",

        // Card 3: Bing Maps Business Finder
        ob_c3_title: "Bing Maps Business Finder",
        ob_c3_ver: "v1.1.0",
        ob_c3_sub: "MS의 지도 데이터를 — 당신의 정교한 영업 DB로",
        ob_c3_desc: "Bing Maps에서 업체를 검색하고 상세 비즈니스 정보를 자동으로 수집합니다. Google Maps와 교차 검증으로 더 정확한 데이터를 확보하세요.",
        ob_c3_t1: "🌐 크로스 검증",
        ob_c3_t2: "📞 연락처 자동발굴",
        ob_c3_t3: "💾 JSON 내보내기",

        // Card 4: XPIDER VPN
        ob_c4_title: "XPIDER VPN",
        ob_c4_ver: "v2.6.0",
        ob_c4_sub: "강력한 보안과 익명성 — 전 세계 어디서든 안전한 탐색",
        ob_c4_desc: "사용자의 IP를 숨기고 고속 프록시 서버를 통해 익명으로 웹을 탐색합니다. 차단된 사이트 우회 및 데이터 수집 시 보안을 강화합니다.",
        ob_c4_t1: "🔒 IP 암호화",
        ob_c4_t2: "🚀 고속 프록시",
        ob_c4_t3: "🌍 글로벌 서버",

        // Card 5: Email Extractor
        ob_c5_title: "Email Extractor",
        ob_c5_ver: "v1.0.0",
        ob_c5_sub: "현재 탭에서 즉시 — 실시간 이메일 발굴 엔진",
        ob_c5_desc: "브라우징 중인 현재 페이지에서 이메일 주소를 실시간으로 감지하고 수집합니다. 탭 이동만으로 방대한 리드 리스트를 구축하세요.",
        ob_c5_t1: "⚡ 실시간 감지",
        ob_c5_t2: "📑 리드 리스트",
        ob_c5_t3: "🔀 교차 탭 수집",

        // Card 6: XPIDER AutoForm Sender Pro
        ob_c6_title: "XPIDER AutoForm Sender",
        ob_c6_ver: "Pro",
        ob_c6_sub: "AI 기반 폼 발송 — 수천 개의 연락처에 자동 도달",
        ob_c6_desc: "비즈니스 문의 폼을 자동으로 감지하고 메시지를 발송하는 고성능 자동화 엔진입니다. 개인화된 캠페인으로 전환율을 극대화하세요.",
        ob_c6_t1: "🤖 AI 필드 감지",
        ob_c6_t2: "📤 대량 발송",
        ob_c6_t3: "🔄 캠페인 관리",

        // Card 7: XPIDER SendForce Mailer Pro
        ob_c7_title: "XPIDER SendForce Mailer",
        ob_c7_ver: "Pro",
        ob_c7_sub: "고속 이메일 마케팅 — 강력한 아웃리치 도구",
        ob_c7_desc: "대량의 이메일을 고속으로 안전하게 발송하는 전문가용 마케팅 엔진입니다. 최적화된 전달 알고리즘으로 성공적인 캠페인을 지원합니다.",
        ob_c7_t1: "🔥 초고속 엔진",
        ob_c7_t2: "📈 도달률 최적화",
        ob_c7_t3: "🛠️ 전문가용 설정",

        history_tab: "방문 기록",
        bookmarks_tab: "즐겨찾기",
        clear_all: "모두 삭제",
        logout_confirm: "로그아웃 하시겠습니까?",
        clear_history_confirm: "방문 기록을 모두 삭제하시겠습니까?",
        clear_emails_confirm: "수집된 모든 이메일을 삭제하시겠습니까?"
    },
    en: {
        app_title: "XPIDER Browser",
        back: "Back",
        forward: "Forward",
        reload: "Reload",
        placeholder_url: "Enter URL or search...",
        themes: "Themes",
        languages: "Languages",
        update_available: "Update available...",
        restart: "Restart",
        add_page: "Add Page",
        hide_sidebar: "Hide Sidebar",
        ob_welcome: "Welcome to XPIDER",
        ob_subline: "The world's most powerful business data collection browser",
        ob_next: "Next",
        ob_close: "Get Started",
        ob_dont_show: "Don't show this again",
        check_update: "Check for Updates",
        welcome_msg: "Welcome to XPIDER Browser",

        // Card 1: Local Business Crawler Pro
        ob_c1_title: "Local Business Crawler",
        ob_c1_ver: "Pro",
        ob_c1_sub: "Across search engines — one company name becomes a complete lead",
        ob_c1_desc: "Search keywords on 10+ engines (Google, Naver, Bing, etc.) and automatically track homepages and contact pages to collect emails, phones, and SNS at once.",
        ob_c1_t1: "🔍 4-Step Deep Scan",
        ob_c1_t2: "📧 Auto Email Extraction",
        ob_c1_t3: "🤖 Auto Captcha Bypass",

        // Card 2: GMaps Business Finder
        ob_c2_title: "GMaps Business Finder",
        ob_c2_ver: "v1.1.0",
        ob_c2_sub: "All businesses on the map — converted into high-quality leads",
        ob_c2_desc: "Explore nearby businesses by keywords on Google Maps and discover business names, ratings, phones, and emails in real-time. Supports CSV/JSON export.",
        ob_c2_t1: "📍 Location-based Capture",
        ob_c2_t2: "⭐ Rating Filter",
        ob_c2_t3: "📊 CSV Export",

        // Card 3: Bing Maps Business Finder
        ob_c3_title: "Bing Maps Business Finder",
        ob_c3_ver: "v1.1.0",
        ob_c3_sub: "Bing Maps data — into your sophisticated sales database",
        ob_c3_desc: "Search businesses on Bing Maps and automatically collect detailed business info. Ensure data accuracy with cross-verification with Google Maps.",
        ob_c3_t1: "🌐 Cross-Verification",
        ob_c3_t2: "📞 Auto Contact Discovery",
        ob_c3_t3: "💾 JSON Export",

        // Card 4: XPIDER VPN
        ob_c4_title: "XPIDER VPN",
        ob_c4_ver: "v2.6.0",
        ob_c4_sub: "Strong security and anonymity — safe exploration anywhere in the world",
        ob_c4_desc: "Hide your IP and browse the web anonymously through high-speed proxy servers. Bypass blocked sites and strengthen security during data collection.",
        ob_c4_t1: "🔒 IP Encryption",
        ob_c4_t2: "🚀 High-speed Proxy",
        ob_c4_t3: "🌍 Global Servers",

        // Card 5: Email Extractor
        ob_c5_title: "Email Extractor",
        ob_c5_ver: "v1.0.0",
        ob_c5_sub: "Instant on current tab — real-time email discovery engine",
        ob_c5_desc: "Detect and collect email addresses in real-time from the current page you're browsing. Build a vast lead list just by moving through tabs.",
        ob_c5_t1: "⚡ Real-time Detection",
        ob_c5_t2: "📑 Lead List",
        ob_c5_t3: "🔀 Cross-tab Capture",

        // Card 6: XPIDER AutoForm Sender Pro
        ob_c6_title: "XPIDER AutoForm Sender",
        ob_c6_ver: "Pro",
        ob_c6_sub: "AI-powered form submission — automatically reach thousands of contacts",
        ob_c6_desc: "High-performance automation engine that detects business inquiry forms and sends messages. Maximize conversion rates with personalized campaigns.",
        ob_c6_t1: "🤖 AI Field Detection",
        ob_c6_t2: "📤 Bulk Sending",
        ob_c6_t3: "🔄 Campaign Management",

        // Card 7: XPIDER SendForce Mailer Pro
        ob_c7_title: "XPIDER SendForce Mailer",
        ob_c7_ver: "Pro",
        ob_c7_sub: "High-speed email marketing — a powerful outreach tool",
        ob_c7_desc: "Professional marketing engine for high-speed, secure bulk email sending. Supports successful campaigns with optimized delivery algorithms.",
        ob_c7_t1: "🔥 High-speed Engine",
        ob_c7_t2: "📈 Delivery Optimization",
        ob_c7_t3: "🛠️ Pro Settings",

        history_tab: "History",
        bookmarks_tab: "Bookmarks",
        clear_all: "Clear All",
        logout_confirm: "Are you sure you want to logout?",
        clear_history_confirm: "Are you sure you want to clear all history?",
        clear_emails_confirm: "Are you sure you want to delete all collected emails?"
    },
    ja: {
        app_title: "XPIDER ブラウザ",
        back: "戻る",
        forward: "進む",
        reload: "再読み込み",
        placeholder_url: "URLを入力または検索...",
        themes: "テーマ",
        languages: "言語",
        update_available: "アップデートがあります...",
        restart: "再起動",
        add_page: "ページ追加",
        hide_sidebar: "サイドバーを隠す",
        ob_welcome: "アプリハイライト",
        ob_next: "次へ",
        ob_close: "閉じる",
        ob_dont_show: "以後表示しない",
        check_update: "アップデートを確認",
        welcome_msg: "XPIDERブラウザへようこそ",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "ウェブページからビジネス情報を一目で収集・抽出する強力なクローラーです。",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "入力された宛先にメッセージを自動送信する効率的なビジネスメッセンジャーです。",
        history_tab: "履歴",
        bookmarks_tab: "ブックマーク",
        downloads_tab: "ダウンロード",
        clear_all: "すべて削除"
    },
    zh: {
        app_title: "XPIDER 浏览器",
        back: "后退",
        forward: "前进",
        reload: "刷新",
        placeholder_url: "输入 URL 或搜索...",
        themes: "主题",
        languages: "语言",
        update_available: "有可用更新...",
        restart: "重启",
        add_page: "添加页面",
        hide_sidebar: "隐藏侧边栏",
        ob_welcome: "应用亮点",
        ob_next: "下一步",
        ob_close: "关闭",
        ob_dont_show: "不再显示",
        check_update: "检查更新",
        welcome_msg: "欢迎使用 XPIDER 浏览器",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "一款功能强大的爬虫，可一目了然地从网页中收集和提取业务信息。",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "一种高效的业务信使，可自动向输入目标发送消息。",
        history_tab: "历史记录",
        bookmarks_tab: "收藏夹",
        downloads_tab: "下载",
        clear_all: "清空所有"
    },
    es: {
        app_title: "Navegador XPIDER",
        back: "Atrás",
        forward: "Adelante",
        reload: "Recargar",
        placeholder_url: "Introduce URL o busca...",
        themes: "Temas",
        languages: "Idiomas",
        update_available: "Actualización disponible...",
        restart: "Reiniciar",
        add_page: "Añadir página",
        hide_sidebar: "Ocultar barra lateral",
        ob_welcome: "Lo más destacado",
        ob_next: "Siguiente",
        ob_close: "Cerrar",
        ob_dont_show: "No volver a mostrar",
        check_update: "Buscar actualizaciones",
        welcome_msg: "Bienvenido al navegador XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un potente rastreador que recopila y extrae información comercial de páginas web de un vistazo.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un mensajero comercial eficiente que envía mensajes automáticamente a los objetivos de entrada.",
        history_tab: "Historial",
        bookmarks_tab: "Marcadores",
        clear_all: "Borrar todo"
    },
    fr: {
        app_title: "Navigateur XPIDER",
        back: "Retour",
        forward: "Suivant",
        reload: "Actualiser",
        placeholder_url: "Entrez l'URL ou recherchez...",
        themes: "Thèmes",
        languages: "Langues",
        update_available: "Mise à jour disponible...",
        restart: "Redémarrer",
        add_page: "Ajouter une page",
        hide_sidebar: "Masquer la barre",
        ob_welcome: "Points forts",
        ob_next: "Suivant",
        ob_close: "Fermer",
        ob_dont_show: "Ne plus afficher",
        check_update: "Vérifier les mises à jour",
        welcome_msg: "Bienvenue sur le navigateur XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un robot d'indexation puissant qui collecte et extrait les informations commerciales des pages Web en un coup d'œil.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un messager professionnel efficace qui envoie automatiquement des messages aux cibles saisies.",
        history_tab: "Historique",
        bookmarks_tab: "Favoris",
        clear_all: "Tout effacer"
    },
    de: {
        app_title: "XPIDER Browser",
        back: "Zurück",
        forward: "Vorwärts",
        reload: "Neu laden",
        placeholder_url: "URL eingeben oder suchen...",
        themes: "Themes",
        languages: "Sprachen",
        update_available: "Update verfügbar...",
        restart: "Neustart",
        add_page: "Seite hinzufügen",
        hide_sidebar: "Seitenleiste ausblenden",
        ob_welcome: "App-Highlights",
        ob_next: "Weiter",
        ob_close: "Schließen",
        ob_dont_show: "Nicht mehr anzeigen",
        check_update: "Nach Updates suchen",
        welcome_msg: "Willkommen beim XPIDER Browser",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Ein leistungsstarker Crawler, der auf einen Blick Geschäftsinformationen von Webseiten sammelt und extrahiert.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Ein effizienter Business-Messenger, der automatisch Nachrichten an die eingegebenen Ziele sendet.",
        history_tab: "Verlauf",
        bookmarks_tab: "Lesezeichen",
        clear_all: "Alles löschen"
    },
    ru: {
        app_title: "Браузер XPIDER",
        back: "Назад",
        forward: "Вперед",
        reload: "Обновить",
        placeholder_url: "Введите URL или поиск...",
        themes: "Темы",
        languages: "Языки",
        update_available: "Доступно обновление...",
        restart: "Перезапуск",
        add_page: "Добавить страницу",
        hide_sidebar: "Скрыть панель",
        ob_welcome: "Особенности",
        ob_next: "Далее",
        ob_close: "Закрыть",
        ob_dont_show: "Больше не показывать",
        check_update: "Проверить обновление",
        welcome_msg: "Добро пожаловать в браузер XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Мощный поисковый робот, который собирает и извлекает деловую информацию с веб-страниц одним взглядом.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Эффективный бизнес-мессенджер, который автоматически отправляет сообщения указанным целям.",
        history_tab: "История",
        bookmarks_tab: "Закладки",
        clear_all: "Очистить всё"
    },
    pt: {
        app_title: "Navegador XPIDER",
        back: "Voltar",
        forward: "Avançar",
        reload: "Recarregar",
        placeholder_url: "Digite URL ou pesquise...",
        themes: "Temas",
        languages: "Idiomas",
        update_available: "Atualização disponível...",
        restart: "Reiniciar",
        add_page: "Adicionar página",
        hide_sidebar: "Ocultar barra lateral",
        ob_welcome: "Destaques",
        ob_next: "Próximo",
        ob_close: "Fechar",
        ob_dont_show: "Não mostrar novamente",
        check_update: "Verificar atualizações",
        welcome_msg: "Bem-vindo ao navegador XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Um rastreador poderoso que coleta e extrai informações comerciais de páginas da web em um relance.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Um mensageiro de negócios eficiente que envia mensagens automaticamente para os alvos inseridos.",
        history_tab: "Histórico",
        bookmarks_tab: "Favoritos",
        clear_all: "Limpar tudo"
    },
    it: {
        app_title: "Browser XPIDER",
        back: "Indietro",
        forward: "Avanti",
        reload: "Ricarica",
        placeholder_url: "Inserisci URL o cerca...",
        themes: "Temi",
        languages: "Lingue",
        update_available: "Aggiornamento disponibile...",
        restart: "Riavvia",
        add_page: "Aggiungi pagina",
        hide_sidebar: "Nascondi barra",
        ob_welcome: "Punti salienti",
        ob_next: "Avanti",
        ob_close: "Chiudi",
        ob_dont_show: "Non mostrare più",
        check_update: "Controlla aggiornamenti",
        welcome_msg: "Benvenuti nel browser XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un potente crawler che raccoglie ed estrae informazioni aziendali dalle pagine Web a colpo d'occhio.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un efficiente messaggero aziendale che invia automaticamente messaggi ai destinatari inseriti.",
        history_tab: "Cronologia",
        bookmarks_tab: "Segnalibri",
        clear_all: "Cancella tutto"
    },
    vi: {
        app_title: "Trình duyệt XPIDER",
        back: "Quay lại",
        forward: "Tiếp tục",
        reload: "Tải lại",
        placeholder_url: "Nhập URL hoặc tìm kiếm...",
        themes: "Chủ đề",
        languages: "Ngôn ngữ",
        update_available: "Có bản cập nhật mới...",
        restart: "Khởi động lại",
        add_page: "Thêm trang",
        hide_sidebar: "Ẩn thanh bên",
        ob_welcome: "Điểm nổi bật",
        ob_next: "Tiếp theo",
        ob_close: "Đóng",
        ob_dont_show: "Không hiển thị lại",
        check_update: "Kiểm tra cập nhật",
        welcome_msg: "Chào mừng bạn đến với Trình duyệt XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Một trình thu thập dữ liệu mạnh mẽ thu thập và trích xuất thông tin kinh doanh từ các trang web trong nháy mắt.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Một trình nhắn tin doanh nghiệp hiệu quả tự động gửi tin nhắn đến các mục tiêu đã nhập.",
        history_tab: "Lịch sử",
        bookmarks_tab: "Dấu trang",
        clear_all: "Xóa tất cả"
    },
    th: {
        app_title: "เบราว์เซอร์ XPIDER",
        back: "ย้อนกลับ",
        forward: "ถัดไป",
        reload: "โหลดใหม่",
        placeholder_url: "ป้อน URL หรือค้นหา...",
        themes: "ธีม",
        languages: "ภาษา",
        update_available: "มีการอัปเดตใหม่...",
        restart: "เริ่มใหม่",
        add_page: "เพิ่มหน้า",
        hide_sidebar: "ซ่อนแถบข้าง",
        ob_welcome: "จุดเด่นของแอป",
        ob_next: "ถัดไป",
        ob_close: "ปิด",
        ob_dont_show: "ไม่ต้องแสดงอีก",
        check_update: "ตรวจสอบการอัปเดต",
        welcome_msg: "ยินดีต้อนรับสู่เบราว์เซอร์ XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "โปรแกรมรวบรวมข้อมูลที่ทรงพลังซึ่งรวบรวมและดึงข้อมูลธุรกิจจากหน้าเว็บได้อย่างรวดเร็ว",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "ผู้ส่งสารทางธุรกิจที่มีประสิทธิภาพซึ่งส่งข้อความไปยังเป้าหมายที่ป้อนโดยอัตโนมัติ",
        history_tab: "ประวัติ",
        bookmarks_tab: "ที่คั่นหน้า",
        clear_all: "ล้างทั้งหมด"
    }
};

if (typeof module !== 'undefined') {
    module.exports = translations;
} else {
    window.translations = translations;
}
