const translations = {
    ko: {
        app_title: "XPIDER 브라우저",
        back: "뒤로",
        forward: "앞으로",
        reload: "새로고침",
        placeholder_url: "URL 입력 또는 검색...",
        themes: "테마",
        languages: "언어",
        update_available: "업데이트 가능...",
        restart: "재시작",
        add_page: "페이지 추가",
        hide_sidebar: "사이드바 숨기기",
        ob_welcome: "앱 하이라이트",
        ob_next: "다음",
        ob_close: "시작하기",
        ob_dont_show: "다시 보지 않기",
        check_update: "업데이트 확인",
        welcome_msg: "XPIDER 브라우저에 오신 것을 환영합니다",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "웹 페이지 내 비즈니스 정보를 한눈에 수집하고 추출하는 강력한 크롤러입니다.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "입력된 대상에게 자동으로 메시지를 발송하는 효율적인 비즈니스 메신저입니다.",
        history_tab: "방문 기록",
        bookmarks_tab: "즐겨찾기",
        clear_all: "모두 삭제",
        ext_email_title: "Email Extractor",
        ext_email_desc: "웹서핑중 모든이메일 주소를 수집하는 강력한 이메일 수집기",
        logout_confirm: "로그아웃 하시겠습니까?",
        clear_history_confirm: "방문 기록을 모두 삭제하시겠습니까?",
        clear_emails_confirm: "수집된 모든 이메일을 삭제하시겠습니까?",
        ob_headline: "XPIDER에 오신 것을 환영합니다",
        ob_subline: "세계 최강의 비즈니스 데이터 수집 브라우저",
        ob_start_now: "지금 시작하기",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "검색엔진을 가로질러 — 업체명 하나가 완전한 리드로",
        ob_ext1_desc: "구글·네이버·빙 등 10개 검색엔진에서 키워드 검색 후, 업체명·홈페이지·컨택 페이지를 자동 추적하여 이메일·전화·주소·SNS까지 한 번에 수집합니다.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "지도 위 모든 업체를 — 고품질 리드 리스트로 변환",
        ob_ext2_desc: "구글 맵에서 검색어로 주변 업체를 탐색하고, 업체명·별점·전화·홈페이지·이메일을 실시간으로 발굴합니다. CSV/JSON 즉시 내보내기 지원.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "MS의 지도 데이터를 — 당신의 정교한 영업 DB로",
        ob_ext3_desc: "Bing Maps에서 업체를 검색하고 상세 비즈니스 정보를 자동으로 수집합니다. Google Maps와 교차 검증으로 더 정확한 데이터를 확보하세요.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "강력한 보안과 익명성 — 전 세계 어디서든 안전한 탐색",
        ob_ext4_desc: "사용자의 IP를 숨기고 고속 프록시 서버를 통해 익명으로 웹을 탐색합니다. 차단된 사이트 우회 및 데이터 수집 시 보안을 강화합니다.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "현재 탭에서 즉시 — 실시간 이메일 발굴 엔진",
        ob_ext5_desc: "브라우징 중인 현재 페이지에서 이메일 주소를 실시간으로 감지하고 수집합니다. 탭 이동만으로 방대한 리드 리스트를 구축하세요.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "AI 기반 폼 발송 — 수천 개의 연락처에 자동 도달",
        ob_ext6_desc: "비즈니스 문의 폼을 자동으로 감지하고 메시지를 발송하는 고성능 자동화 엔진입니다. 개인화된 캠페인으로 전환율을 극대화하세요.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "고속 이메일 마케팅 — 강력한 아웃리치 도구",
        ob_ext7_desc: "대량의 이메일을 고속으로 안전하게 발송하는 전문가용 마케팅 엔진입니다. 최적화된 전달 알고리즘으로 성공적인 캠페인을 지원합니다."
    },
    en: {
        app_title: "XPIDER Browser",
        back: "Back",
        forward: "Forward",
        reload: "Reload",
        placeholder_url: "Enter URL or search...",
        themes: "Themes",
        languages: "Languages",
        update_available: "Update available...",
        restart: "Restart",
        add_page: "Add Page",
        hide_sidebar: "Hide Sidebar",
        ob_welcome: "App Highlights",
        ob_next: "Next",
        ob_close: "Close",
        ob_dont_show: "Don't show this again",
        check_update: "Check for Updates",
        welcome_msg: "Welcome to XPIDER Browser",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "A powerful crawler that collects and extracts business information from web pages at a glance.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "An efficient business messenger that automatically sends messages to the input targets.",
        history_tab: "History",
        bookmarks_tab: "Bookmarks",
        clear_all: "Clear All",
        ext_email_title: "Email Extractor",
        ext_email_desc: "A powerful email collector that gathers all email addresses while surfing the web.",
        logout_confirm: "Are you sure you want to logout?",
        clear_history_confirm: "Are you sure you want to clear all history?",
        clear_emails_confirm: "Are you sure you want to delete all collected emails?",
        ob_headline: "Welcome to XPIDER",
        ob_subline: "The World's Most Powerful Business Data Collection Browser",
        ob_start_now: "Start Now",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Across Search Engines — One business name into a complete lead",
        ob_ext1_desc: "Search keywords across 10 search engines including Google, Naver, and Bing, then automatically track business names and contact pages to collect emails, phones, and social media at once.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "All Businesses on the Map — Transformed into high-quality lead lists",
        ob_ext2_desc: "Explore nearby businesses on Google Maps and discover names, ratings, phones, and emails in real-time. Supports instant CSV/JSON export.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "MS Map Data — Into your sophisticated sales database",
        ob_ext3_desc: "Search for businesses on Bing Maps and automatically collect detailed information. Secure more accurate data through cross-validation with Google Maps.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Strong Security and Anonymity — Safe browsing anywhere in the world",
        ob_ext4_desc: "Hide your IP and browse the web anonymously through high-speed proxy servers. Enhance security when bypassing blocked sites.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Instantly on Current Tab — Real-time email discovery engine",
        ob_ext5_desc: "Detect and collect email addresses in real-time on the current page. Build a massive lead list just by moving tabs.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "AI-based Form Sending — Reach thousands of contacts automatically",
        ob_ext6_desc: "A high-performance automation engine that automatically detects business inquiry forms and sends messages.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "High-speed Email Marketing — Powerful outreach tool",
        ob_ext7_desc: "A professional marketing engine that sends large volumes of emails safely at high speed with optimized delivery."
    },
    ja: {
        app_title: "XPIDER ブラウザ",
        back: "戻る",
        forward: "進む",
        reload: "再読み込み",
        placeholder_url: "URLを入力または検索...",
        themes: "テーマ",
        languages: "言語",
        update_available: "アップデートがあります...",
        restart: "再起動",
        add_page: "ページ追加",
        hide_sidebar: "サイドバーを隠す",
        ob_welcome: "アプリハイライト",
        ob_next: "次へ",
        ob_close: "閉じる",
        ob_dont_show: "以後表示しない",
        check_update: "アップデートを確認",
        welcome_msg: "XPIDERブラウザへようこそ",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "ウェブページからビジネス情報を一目で収集・抽出する強力なクローラーです。",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "入力された宛先にメッセージを自動送信する効率的なビジネスメッセンジャーです。",
        history_tab: "履歴",
        bookmarks_tab: "ブックマーク",
        downloads_tab: "ダウンロード",
        clear_all: "すべて削除",
        ob_headline: "XPIDERへようこそ",
        ob_subline: "世界最強のビジネスデータ収集ブラウザ",
        ob_start_now: "今すぐ開始",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "検索エンジンを超えて — 1つの会社名が完全なリードに",
        ob_ext1_desc: "Google、Naver、Bingなど10の検索エンジンでキーワードを検索し、会社名や連絡先ページを自動追跡してメールや電話を一括収集します。",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "地図上のすべてのビジネスを — 高品質なリードリストに変換",
        ob_ext2_desc: "Googleマップで周辺のビジネスを探索し、名前、評価、電話、メールをリアルタイムで発見します。CSV/JSON書き出し対応。",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "MS地図データ — 洗練された営業データベースへ",
        ob_ext3_desc: "Bing Mapsでビジネスを検索し、詳細情報を自動収集します。Google Mapsとの相互検証により、より正確なデータを確保します。",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "強力なセキュリティと匿名性 — 世界中どこでも安全なブラウジング",
        ob_ext4_desc: "IPを隠し、高速プロキシサーバーを介して匿名でウェブを閲覧します。ブロックされたサイトの回避やデータ収集時のセキュリティを強化します。",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "現在のタブで即座に — リアルタイムメール発見エンジン",
        ob_ext5_desc: "閲覧中のページからメールアドレスをリアルタイムで検出・収集します。タブを移動するだけで膨大なリードリストを構築できます。",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "AIベースのフォーム送信 — 何千もの連絡先に自動アプローチ",
        ob_ext6_desc: "ビジネス問い合わせフォームを自動検出し、メッセージを送信する高性能自動化エンジンです。パーソナライズされたキャンペーンで転換率を最大化します。",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "高速メールマーケティング — 強力なアウトリーチツール",
        ob_ext7_desc: "大量のメールを高速かつ安全に送信するプロフェッショナル向けマーケティングエンジンです。最適化された配信アルゴリズムをサポートします。"
    },
    zh: {
        app_title: "XPIDER 浏览器",
        back: "后退",
        forward: "前进",
        reload: "刷新",
        placeholder_url: "输入 URL 或搜索...",
        themes: "主题",
        languages: "语言",
        update_available: "有可用更新...",
        restart: "重启",
        add_page: "添加页面",
        hide_sidebar: "隐藏侧边栏",
        ob_welcome: "应用亮点",
        ob_next: "下一步",
        ob_close: "关闭",
        ob_dont_show: "不再显示",
        check_update: "检查更新",
        welcome_msg: "欢迎使用 XPIDER 浏览器",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "一款功能强大的爬虫，可一目了然地从网页中收集和提取业务信息。",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "一种高效的业务信使，可自动向输入目标发送消息。",
        history_tab: "历史记录",
        bookmarks_tab: "收藏夹",
        downloads_tab: "下载",
        clear_all: "清空所有",
        ob_headline: "欢迎来到 XPIDER",
        ob_subline: "全球最强大的业务数据采集浏览器",
        ob_start_now: "立即开始",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "跨越搜索引擎 — 一个公司名称即可成为完整潜在客户",
        ob_ext1_desc: "在 Google、Naver、Bing 等 10 个搜索引擎中搜索关键词，自动追踪公司名称和联系页面，一次性收集电子邮件、电话等信息。",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "地图上的所有商家 — 转换为高质量潜在客户列表",
        ob_ext2_desc: "在 Google 地图上探索周边商家，实时发现名称、评分、电话和电子邮件。支持即时导出 CSV/JSON。",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "MS 地图数据 — 存入您的精细销售数据库",
        ob_ext3_desc: "在 Bing Maps 上搜索商家并自动收集详细信息。通过与 Google Maps 的交叉验证确保数据更准确。",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "强大的安全性与匿名性 — 在世界任何地方安全浏览",
        ob_ext4_desc: "隐藏您的 IP，通过高速代理服务器匿名浏览网页。在绕过被屏蔽网站和收集数据时增强安全性。",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "当前标签页即刻获取 — 实时电子邮件发现引擎",
        ob_ext5_desc: "在浏览当前页面时实时检测并收集电子邮件地址。只需切换标签页即可构建庞大的潜在客户列表。",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "基于 AI 的表单发送 — 自动触达数千个联系人",
        ob_ext6_desc: "自动检测业务咨询表单并发送消息的高性能自动化引擎。通过个性化活动最大化转化率。",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "高速电子邮件营销 — 强大的外联工具",
        ob_ext7_desc: "专业营销引擎，高速安全地发送大量电子邮件。通过优化的传递算法支持成功的营销活动。"
    },
    es: {
        app_title: "Navegador XPIDER",
        back: "Atrás",
        forward: "Adelante",
        reload: "Recargar",
        placeholder_url: "Introduce URL o busca...",
        themes: "Temas",
        languages: "Idiomas",
        update_available: "Actualización disponible...",
        restart: "Reiniciar",
        add_page: "Añadir página",
        hide_sidebar: "Ocultar barra lateral",
        ob_welcome: "Lo más destacado",
        ob_next: "Siguiente",
        ob_close: "Cerrar",
        ob_dont_show: "No volver a mostrar",
        check_update: "Buscar actualizaciones",
        welcome_msg: "Bienvenido al navegador XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un potente rastreador que recopila y extrae información comercial de páginas web de un vistazo.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un mensajero comercial eficiente que envía mensajes automáticamente a los objetivos de entrada.",
        history_tab: "Historial",
        bookmarks_tab: "Marcadores",
        clear_all: "Borrar todo",
        ob_headline: "Bienvenido a XPIDER",
        ob_subline: "El navegador de recopilación de datos comerciales más potente del mundo",
        ob_start_now: "Empezar ahora",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "A través de motores de búsqueda — Un nombre de empresa en un cliente potencial completo",
        ob_ext1_desc: "Busque palabras clave en 10 motores de búsqueda, incluidos Google, Naver y Bing, luego rastree automáticamente los nombres de las empresas para recopilar correos electrónicos y teléfonos.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Todos los negocios en el mapa — Transformados en listas de clientes potenciales de alta calidad",
        ob_ext2_desc: "Explore negocios cercanos en Google Maps y descubra nombres, calificaciones, teléfonos y correos electrónicos en tiempo real. Exportación CSV/JSON instantánea.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Datos de mapas de MS — En su sofisticada base de datos de ventas",
        ob_ext3_desc: "Busque empresas en Bing Maps y recopile información detallada automáticamente. Obtenga datos más precisos mediante la validación cruzada con Google Maps.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Seguridad y anonimato potentes — Navegación segura en cualquier lugar",
        ob_ext4_desc: "Oculte su IP y navegue de forma anónima a través de servidores proxy de alta velocidad. Mejore la seguridad al recopilar datos.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Al instante en la pestaña actual — Motor de descubrimiento de correo en tiempo real",
        ob_ext5_desc: "Detecte y recopile correos electrónicos en tiempo real en la página actual. Cree una lista masiva de clientes potenciales con solo mover pestañas.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Envío de formularios basado en IA — Llegue a miles de contactos automáticamente",
        ob_ext6_desc: "Motor de automatización de alto rendimiento que detecta formularios de consulta y envía mensajes. Maximice las tasas de conversión.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "Marketing por correo de alta velocidad — Potente herramienta de alcance",
        ob_ext7_desc: "Motor de marketing profesional que envía grandes volúmenes de correos de forma segura a alta velocidad."
    },
    fr: {
        app_title: "Navigateur XPIDER",
        back: "Retour",
        forward: "Suivant",
        reload: "Actualiser",
        placeholder_url: "Entrez l'URL ou recherchez...",
        themes: "Thèmes",
        languages: "Langues",
        update_available: "Mise à jour disponible...",
        restart: "Redémarrer",
        add_page: "Ajouter une page",
        hide_sidebar: "Masquer la barre",
        ob_welcome: "Points forts",
        ob_next: "Suivant",
        ob_close: "Fermer",
        ob_dont_show: "Ne plus afficher",
        check_update: "Vérifier les mises à jour",
        welcome_msg: "Bienvenue sur le navigateur XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un robot d'indexation puissant qui collecte et extrait les informations commerciales des pages Web en un coup d'œil.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un messager professionnel efficace qui envoie automatiquement des messages aux cibles saisies.",
        history_tab: "Historique",
        bookmarks_tab: "Favoris",
        clear_all: "Tout effacer",
        ob_headline: "Bienvenue sur XPIDER",
        ob_subline: "Le navigateur de collecte de données professionnelles le plus puissant au monde",
        ob_start_now: "Démarrer maintenant",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "À travers les moteurs de recherche — Un nom d'entreprise en un prospect complet",
        ob_ext1_desc: "Recherchez des mots-clés sur 10 moteurs de recherche, puis suivez automatiquement les noms d'entreprises pour collecter les e-mails et les téléphones.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Toutes les entreprises sur la carte — Transformées en listes de prospects de haute qualité",
        ob_ext2_desc: "Explorez les entreprises à proximité sur Google Maps et découvrez les noms, les avis, les téléphones et les e-mails en temps réel.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Données cartographiques MS — Dans votre base de données de vente sophistiquée",
        ob_ext3_desc: "Recherchez des entreprises sur Bing Maps et collectez des informations détaillées automatiquement.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Sécurité et anonymat puissants — Navigation sécurisée partout dans le monde",
        ob_ext4_desc: "Masquez votre IP et naviguez de manière anonyme via des serveurs proxy haut débit.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Instantanément sur l'onglet actuel — Moteur de découverte d'e-mails en temps réel",
        ob_ext5_desc: "Détectez et collectez les adresses e-mail en temps réel sur la page actuelle.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Envoi de formulaires basé sur l'IA — Atteignez des milliers de contacts automatiquement",
        ob_ext6_desc: "Moteur d'automatisation haute performance qui détecte les formulaires de demande et envoie des messages.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "E-mail marketing haute vitesse — Puissant outil de sensibilisation",
        ob_ext7_desc: "Moteur de marketing professionnel qui envoie de gros volumes d'e-mails en toute sécurité."
    },
    de: {
        app_title: "XPIDER Browser",
        back: "Zurück",
        forward: "Vorwärts",
        reload: "Neu laden",
        placeholder_url: "URL eingeben oder suchen...",
        themes: "Themes",
        languages: "Sprachen",
        update_available: "Update verfügbar...",
        restart: "Neustart",
        add_page: "Seite hinzufügen",
        hide_sidebar: "Seitenleiste ausblenden",
        ob_welcome: "App-Highlights",
        ob_next: "Weiter",
        ob_close: "Schließen",
        ob_dont_show: "Nicht mehr anzeigen",
        check_update: "Nach Updates suchen",
        welcome_msg: "Willkommen beim XPIDER Browser",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Ein leistungsstarker Crawler, der auf einen Blick Geschäftsinformationen von Webseiten sammelt und extrahiert.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Ein effizienter Business-Messenger, der automatisch Nachrichten an die eingegebenen Ziele sendet.",
        history_tab: "Verlauf",
        bookmarks_tab: "Lesezeichen",
        clear_all: "Alles löschen",
        ob_headline: "Willkommen bei XPIDER",
        ob_subline: "Der weltweit leistungsstärkste Browser zur Erfassung von Geschäftsdaten",
        ob_start_now: "Jetzt starten",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Suchmaschinenübergreifend — Ein Firmenname wird zum vollständigen Lead",
        ob_ext1_desc: "Suchen Sie nach Schlüsselwörtern in 10 Suchmaschinen und verfolgen Sie automatisch Firmennamen, um E-Mails und Telefone zu sammeln.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Alle Unternehmen auf der Karte — Umgewandelt in hochwertige Lead-Listen",
        ob_ext2_desc: "Erkunden Sie Unternehmen in der Nähe auf Google Maps und entdecken Sie Namen, Bewertungen und E-Mails in Echtzeit.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "MS-Kartendaten — In Ihre anspruchsvolle Vertriebsdatenbank",
        ob_ext3_desc: "Suchen Sie nach Unternehmen auf Bing Maps und sammeln Sie automatisch detaillierte Informationen.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Starke Sicherheit und Anonymität — Sicheres Surfen weltweit",
        ob_ext4_desc: "Verbergen Sie Ihre IP und surfen Sie anonym über Hochgeschwindigkeits-Proxyserver.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Sofort im aktuellen Tab — Echtzeit-E-Mail-Erkennungs-Engine",
        ob_ext5_desc: "Erkennen und sammeln Sie E-Mail-Adressen in Echtzeit auf der aktuellen Seite.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "KI-basiertes Formularsenden — Tausende Kontakte automatisch erreichen",
        ob_ext6_desc: "Hochleistungs-Automatisierungs-Engine, die Formulare erkennt und Nachrichten sendet.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "Hochgeschwindigkeits-E-Mail-Marketing — Leistungsstarkes Outreach-Tool",
        ob_ext7_desc: "Professionelle Marketing-Engine, die große Mengen an E-Mails sicher und schnell versendet."
    },
    ru: {
        app_title: "Браузер XPIDER",
        back: "Назад",
        forward: "Вперед",
        reload: "Обновить",
        placeholder_url: "Введите URL или поиск...",
        themes: "Темы",
        languages: "Языки",
        update_available: "Доступно обновление...",
        restart: "Перезапуск",
        add_page: "Добавить страницу",
        hide_sidebar: "Скрыть панель",
        ob_welcome: "Особенности",
        ob_next: "Далее",
        ob_close: "Закрыть",
        ob_dont_show: "Больше не показывать",
        check_update: "Проверить обновление",
        welcome_msg: "Добро пожаловать в браузер XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Мощный поисковый робот, который собирает и извлекает деловую информацию с веб-страниц одним взглядом.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Эффективный бизнес-мессенджер, который автоматически отправляет сообщения указанным целям.",
        history_tab: "История",
        bookmarks_tab: "Закладки",
        clear_all: "Очистить всё",
        ob_headline: "Добро пожаловать в XPIDER",
        ob_subline: "Самый мощный в мире браузер для сбора бизнес-данных",
        ob_start_now: "Начать сейчас",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Через поисковые системы — Одно название компании в готовый лид",
        ob_ext1_desc: "Поиск по ключевым словам в 10 поисковых системах с автоматическим сбором email и телефонов компаний.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Все компании на карте — В качественные списки лидов",
        ob_ext2_desc: "Ищите компании на Google Maps и находите названия, рейтинги и контакты в реальном времени.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Данные карт MS — В вашу базу данных продаж",
        ob_ext3_desc: "Автоматический сбор подробной информации о компаниях с Bing Maps.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Безопасность и анонимность — Безопасный веб-серфинг по всему миру",
        ob_ext4_desc: "Скройте свой IP и просматривайте веб-страницы анонимно через высокоскоростные прокси-серверы.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Мгновенно в текущей вкладке — Движок поиска email в реальном времени",
        ob_ext5_desc: "Обнаружение и сбор адресов электронной почты в реальном времени на текущей странице.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Рассылка форм на базе ИИ — Автоматический охват тысяч контактов",
        ob_ext6_desc: "Автоматическое обнаружение форм обратной связи и отправка сообщений.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "Скоростной email-маркетинг — Мощный инструмент охвата",
        ob_ext7_desc: "Профессиональный движок для безопасной и быстрой рассылки больших объемов email."
    },
    pt: {
        app_title: "Navegador XPIDER",
        back: "Voltar",
        forward: "Avançar",
        reload: "Recarregar",
        placeholder_url: "Digite URL ou pesquise...",
        themes: "Temas",
        languages: "Idiomas",
        update_available: "Atualização disponível...",
        restart: "Reiniciar",
        add_page: "Adicionar página",
        hide_sidebar: "Ocultar barra lateral",
        ob_welcome: "Destaques",
        ob_next: "Próximo",
        ob_close: "Fechar",
        ob_dont_show: "Não mostrar novamente",
        check_update: "Verificar atualizações",
        welcome_msg: "Bem-vindo ao navegador XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Um rastreador poderoso que coleta e extrai informações comerciais de páginas da web em um relance.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Um mensageiro de negócios eficiente que envia mensagens automaticamente para os alvos inseridos.",
        history_tab: "Histórico",
        bookmarks_tab: "Favoritos",
        clear_all: "Limpar tudo",
        ob_headline: "Bem-vindo ao XPIDER",
        ob_subline: "O navegador de coleta de dados comerciais mais poderoso do mundo",
        ob_start_now: "Começar agora",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Através de motores de busca — Um nome de empresa em um lead completo",
        ob_ext1_desc: "Pesquise palavras-chave em 10 motores de busca e colete e-mails e telefones de empresas automaticamente.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Todas as empresas no mapa — Transformadas em listas de leads de alta qualidade",
        ob_ext2_desc: "Explore empresas próximas no Google Maps e descubra nomes, avaliações e e-mails em tempo real.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Dados de mapas da MS — Para seu banco de dados de vendas sofisticado",
        ob_ext3_desc: "Pesquise empresas no Bing Maps e colete informações detalhadas automaticamente.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Segurança e anonimato fortes — Navegação segura em qualquer lugar",
        ob_ext4_desc: "Esconda seu IP e navegue anonimamente através de servidores proxy de alta velocidade.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Instantaneamente na guia atual — Motor de descoberta de e-mail em tempo real",
        ob_ext5_desc: "Detecte e colete endereços de e-mail em tempo real na página atual.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Envio de formulários baseado em IA — Alcance milhares de contatos automaticamente",
        ob_ext6_desc: "Motor de automação de alto desempenho que detecta formulários e envia mensagens.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "E-mail marketing de alta velocidade — Ferramenta de alcance poderosa",
        ob_ext7_desc: "Motor de marketing profissional que envia grandes volumes de e-mails com segurança."
    },
    it: {
        app_title: "Browser XPIDER",
        back: "Indietro",
        forward: "Avanti",
        reload: "Ricarica",
        placeholder_url: "Inserisci URL o cerca...",
        themes: "Temi",
        languages: "Lingue",
        update_available: "Aggiornamento disponibile...",
        restart: "Riavvia",
        add_page: "Aggiungi pagina",
        hide_sidebar: "Nascondi barra",
        ob_welcome: "Punti salienti",
        ob_next: "Avanti",
        ob_close: "Chiudi",
        ob_dont_show: "Non mostrare più",
        check_update: "Controlla aggiornamenti",
        welcome_msg: "Benvenuti nel browser XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Un potente crawler che raccoglie ed estrae informazioni aziendali dalle pagine Web a colpo d'occhio.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Un efficiente messaggero aziendale che invia automaticamente messaggi ai destinatari inseriti.",
        history_tab: "Cronologia",
        bookmarks_tab: "Segnalibri",
        clear_all: "Cancella tutto",
        ob_headline: "Benvenuti in XPIDER",
        ob_subline: "Il browser per la raccolta di dati aziendali più potente al mondo",
        ob_start_now: "Inizia ora",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Attraverso i motori di ricerca — Un nome di azienda in un lead completo",
        ob_ext1_desc: "Cerca parole chiave in 10 motori di ricerca e raccogli automaticamente email e telefoni delle aziende.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Tutte le attività sulla mappa — Trasformate in elenchi di lead di alta qualità",
        ob_ext2_desc: "Esplora le attività vicine su Google Maps e scopri nomi, valutazioni ed email in tempo reale.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Dati cartografici MS — Nel tuo sofisticato database di vendita",
        ob_ext3_desc: "Cerca attività su Bing Maps e raccogli informazioni dettagliate automaticamente.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Sicurezza e anonimato forti — Navigazione sicura ovunque",
        ob_ext4_desc: "Nascondi il tuo IP e naviga in modo anonimo tramite server proxy ad alta velocità.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Istantaneamente sulla scheda corrente — Motore di scoperta email in tempo real",
        ob_ext5_desc: "Rileva e raccogli indirizzi email in tempo reale sulla pagina corrente.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Invio di moduli basato su IA — Raggiungi migliaia di contatti automaticamente",
        ob_ext6_desc: "Motore di automazione ad alte prestazioni che rileva moduli e invia messaggi.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "Email marketing ad alta velocità — Potente strumento di outreach",
        ob_ext7_desc: "Motore di marketing professionale per l'invio sicuro di grandi volumi di email."
    },
    vi: {
        app_title: "Trình duyệt XPIDER",
        back: "Quay lại",
        forward: "Tiếp tục",
        reload: "Tải lại",
        placeholder_url: "Nhập URL hoặc tìm kiếm...",
        themes: "Chủ đề",
        languages: "Ngôn ngữ",
        update_available: "Có bản cập nhật mới...",
        restart: "Khởi động lại",
        add_page: "Thêm trang",
        hide_sidebar: "Ẩn thanh bên",
        ob_welcome: "Điểm nổi bật",
        ob_next: "Tiếp theo",
        ob_close: "Đóng",
        ob_dont_show: "Không hiển thị lại",
        check_update: "Kiểm tra cập nhật",
        welcome_msg: "Chào mừng bạn đến với Trình duyệt XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "Một trình thu thập dữ liệu mạnh mẽ thu thập và trích xuất thông tin kinh doanh từ các trang web trong nháy mắt.",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "Một trình nhắn tin doanh nghiệp hiệu quả tự động gửi tin nhắn đến các mục tiêu đã nhập.",
        history_tab: "Lịch sử",
        bookmarks_tab: "Dấu trang",
        clear_all: "Xóa tất cả",
        ob_headline: "Chào mừng bạn đến với XPIDER",
        ob_subline: "Trình duyệt thu thập dữ liệu kinh doanh mạnh mẽ nhất thế giới",
        ob_start_now: "Bắt đầu ngay",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "Trên các công cụ tìm kiếm — Một tên doanh nghiệp thành một khách hàng tiềm năng",
        ob_ext1_desc: "Tìm kiếm từ khóa trên 10 công cụ tìm kiếm và tự động thu thập email, số điện thoại doanh nghiệp.",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "Mọi doanh nghiệp trên bản đồ — Chuyển thành danh sách khách hàng tiềm năng chất lượng",
        ob_ext2_desc: "Khám phá các doanh nghiệp trên Google Maps và tìm thấy tên, đánh giá, email trong thời gian thực.",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "Dữ liệu bản đồ MS — Vào cơ sở dữ liệu bán hàng tinh vi của bạn",
        ob_ext3_desc: "Tìm kiếm doanh nghiệp trên Bing Maps và tự động thu thập thông tin chi tiết.",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "Bảo mật và ẩn danh mạnh mẽ — Duyệt web an toàn ở mọi nơi",
        ob_ext4_desc: "Ẩn IP của bạn và duyệt web ẩn danh qua máy chủ proxy tốc độ cao.",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "Ngay lập tức trên tab hiện tại — Công cụ tìm kiếm email thời gian thực",
        ob_ext5_desc: "Phát hiện và thu thập địa chỉ email trong thời gian thực trên trang hiện tại.",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "Gửi biểu mẫu dựa trên AI — Tự động tiếp cận hàng ngàn liên hệ",
        ob_ext6_desc: "Công cụ tự động hóa hiệu suất cao giúp phát hiện biểu mẫu và gửi tin nhắn.",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "Tiếp thị email tốc độ cao — Công cụ tiếp cận mạnh mẽ",
        ob_ext7_desc: "Công cụ tiếp thị chuyên nghiệp giúp gửi khối lượng lớn email an toàn."
    },
    th: {
        app_title: "เบราว์เซอร์ XPIDER",
        back: "ย้อนกลับ",
        forward: "ถัดไป",
        reload: "โหลดใหม่",
        placeholder_url: "ป้อน URL หรือค้นหา...",
        themes: "ธีม",
        languages: "ภาษา",
        update_available: "มีการอัปเดตใหม่...",
        restart: "เริ่มใหม่",
        add_page: "เพิ่มหน้า",
        hide_sidebar: "ซ่อนแถบข้าง",
        ob_welcome: "จุดเด่นของแอป",
        ob_next: "ถัดไป",
        ob_close: "ปิด",
        ob_dont_show: "ไม่ต้องแสดงอีก",
        check_update: "ตรวจสอบการอัปเดต",
        welcome_msg: "ยินดีต้อนรับสู่เบราว์เซอร์ XPIDER",
        ext_collect_title: "Business Data Crawler",
        ext_collect_desc: "โปรแกรมรวบรวมข้อมูลที่ทรงพลังซึ่งรวบรวมและดึงข้อมูลธุรกิจจากหน้าเว็บได้อย่างรวดเร็ว",
        ext_send_title: "XPIDER Send Pro",
        ext_send_desc: "ผู้ส่งสารทางธุรกิจที่มีประสิทธิภาพซึ่งส่งข้อความไปยังเป้าหมายที่ป้อนโดยอัตโนมัติ",
        history_tab: "ประวัติ",
        bookmarks_tab: "ที่คั่นหน้า",
        clear_all: "ล้างทั้งหมด",
        ob_headline: "ยินดีต้อนรับสู่ XPIDER",
        ob_subline: "เบราว์เซอร์รวบรวมข้อมูลธุรกิจที่ทรงพลังที่สุดในโลก",
        ob_start_now: "เริ่มเลยตอนนี้",
        ob_ext1_name: "Local Business Crawler Pro",
        ob_ext1_sub: "ข้ามเครื่องมือค้นหา — ชื่อธุรกิจเดียวกลายเป็นรีดที่สมบูรณ์",
        ob_ext1_desc: "ค้นหาคีย์เวิร์ดใน 10 เครื่องมือค้นหาและรวบรวมอีเมลและโทรศัพท์ธุรกิจโดยอัตโนมัติ",
        ob_ext2_name: "GMaps Business Finder",
        ob_ext2_sub: "ธุรกิจทั้งหมดบนแผนที่ — เปลี่ยนเป็นรายการรีดคุณภาพสูง",
        ob_ext2_desc: "สำรวจธุรกิจบน Google Maps และค้นหาชื่อ เรตติ้ง และอีเมลแบบเรียลไทม์",
        ob_ext3_name: "Bing Maps Business Finder",
        ob_ext3_sub: "ข้อมูลแผนที่ MS — เข้าสู่ฐานข้อมูลการขายที่ซับซ้อนของคุณ",
        ob_ext3_desc: "ค้นหาธุรกิจบน Bing Maps และรวบรวมข้อมูลโดยละเอียดโดยอัตโนมัติ",
        ob_ext4_name: "XPIDER VPN",
        ob_ext4_sub: "ความปลอดภัยและการปกปิดตัวตน — ท่องเว็บอย่างปลอดภัยทั่วโลก",
        ob_ext4_desc: "ซ่อน IP ของคุณและท่องเว็บโดยไม่ระบุตัวตนผ่านพร็อกซีเซิร์ฟเวอร์ความเร็วสูง",
        ob_ext5_name: "Email Extractor",
        ob_ext5_sub: "ทันทีในแท็บปัจจุบัน — เครื่องมือค้นหาอีเมลแบบเรียลไทม์",
        ob_ext5_desc: "ตรวจจับและรวบรวมที่อยู่อีเมลแบบเรียลไทม์ในหน้าปัจจุบัน",
        ob_ext6_name: "XPIDER AutoForm Sender Pro",
        ob_ext6_sub: "การส่งฟอร์มด้วย AI — เข้าถึงผู้ติดต่อหลายพันรายโดยอัตโนมัติ",
        ob_ext6_desc: "เครื่องมืออัตโนมัติประสิทธิภาพสูงที่ตรวจจับฟอร์มและส่งข้อความ",
        ob_ext7_name: "XPIDER SendForce Mailer Pro",
        ob_ext7_sub: "การตลาดผ่านอีเมลความเร็วสูง — เครื่องมือสื่อสารที่ทรงพลัง",
        ob_ext7_desc: "เครื่องมือการตลาดระดับมืออาชีพที่ส่งอีเมลปริมาณมากอย่างปลอดภัยและรวดเร็ว"
    }
};

if (typeof module !== 'undefined') {
    module.exports = translations;
} else {
    window.translations = translations;
}
